# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
require "pry"

def fibonacci(my_index)
	my_array = Array(1..my_index)
	i = 0
	x = 1

			while i < my_index
				my_array[x+1] = my_array[i] + my_array[i+1]
				i += 1
				x += 1
			end

			puts my_array 

			my_array.delete_if &:odd?
			puts "xxxxx"
			puts my_array
			sum = my_array.reduce(:+)
			puts "xxxxx"

			

			# my_array.each do |x|
			# 	if x.even?
			# 		sum = sum + x 
			# 	end
			# 	return sum
			# end
			puts sum

end

fibonacci(10)
# fibonacci(300)
puts ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

# binding.pry