$(document).ready(function(){
	console.log("Loaded Bro");
	// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

	fibonacci(10);
});



function fibonacci(spots) {
	var fibArray = new Array(spots);
	var total = 0;
	for(var i=0; i<fibArray.length; i++){
		if(i<2){
			fibArray[i] = i+1;
		}
		else {
			fibArray[i] = fibArray[i-2] + fibArray[i-1];
		}
		if (fibArray[i] % 2 == 0){
			total += fibArray[i];
		}
	}
	console.log(fibArray);
	console.log(total);
};